### ISSUE TITLE
Not ble to build my dapp

### ISSUE THREAD

**Issue by Sahityaaryan** [NomicFoundation/solidity-analyzer#15]
./node_modules/@nomicfoundation/solidity-analyzer-win32-x64-msvc/solidity-analyzer.win32-x64-msvc.node
Module parse failed: Unexpected character '�' (1:2)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)

**Comment by fvictorio** [comment]
Closing this for lack of reproduction steps; I will re-open it if you can share a 
[minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).
